version: '3'
services:
    postgres:
        image: postgis/postgis:13-3.2
        environment: 
            - POSTGRES_DB=mugip
            - POSTGRES_USER=mugip
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:35000:5432"
    redis:
        image: redis:latest
        ports:
            - "127.0.0.1:35100:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local
