version: '3'
services:
    postgres:
        image: postgres:13
        environment: 
            - POSTGRES_DB=mugip
            - POSTGRES_USER=mugip
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:35000:5432"
    redis:
        image: redis:latest
        ports:
            - "127.0.0.1:35100:6379"
        command: redis-server --save ""
    elasticsearch:
        image: elasticsearch:7.14.0
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data        
        ports:
            - 9200:9200

volumes:
    postgres-data:
        driver: local
    elasticsearch-data:
        driver: local
